config/routes.rb
Rails.application.routes.draw do
  get 'users/new'
  root 'users#new'


  get 'auth/:provider/callback' => 'sessions#create'
  get 'auth/facebook', as: 'facebook_login'

  get 'logout' => 'sessions#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  validates :provider, presence: true
  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["name"]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private

  # make this method accessible in any controller
  def current_user
    # memoization (caching) technique
    # multiple calls to this method will result in only one database query
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  # make this method acccessible in any view
  helper_method :current_user
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    # omniauth stores data in the request.env instead of params
    auth = request.env["omniauth.auth"]

    # even though this is a login action, an OAuth login can be a login *or* a registration
    #
    # if the user exists, log her in
    # if the user doesn't exist, create her, then log her in
    user =
    User.find_by(provider: auth['provider'], uid: auth['uid']) ||
    User.create_with_omniauth(auth)

    session[:user_id] = user.id
    redirect_to root_url, notice: "Signed in!"
  end

  # logout
  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Signed out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AuthExampleV2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<em><%= notice %></em><br>
<% if current_user %>
  Welcome <%= current_user.name %> you have successfully signed in!<br>
  <%= link_to "Sign out", logout_path %>
<% else %>
  You are not signed in.<br>
  <%= link_to "Sign in with Facebook", facebook_login_path %><br>
<% end %>